SistemaFinanceiro/Controllers/FinanceiroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using SistemaFinanceiro.Models;

namespace SistemaFinanceiro.Controllers
{
    [Authorize]
    public class FinanceiroController : Controller
    {
        private AppDbContext _Context;

        public FinanceiroController(AppDbContext context)
        {
            _Context = context;
        }
        
        // GET: Financeiro
        public ActionResult Index()
        {
            return View(_Context.Financeriros.ToList());
        }


        // GET: Financeiro/Edit/5
        public ActionResult Edit(int? id)
        {
            AjusteContextoEditar();

            if (id > 0)
            {
                return View(_Context.Financeriros.Find(id));
            }
            else
            {
                return View(new Financeriros());
            }
        }

        // POST: Financeiro/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Financeriros terceiros)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (terceiros.Id > 0)
                    {
                        _Context.Entry(terceiros).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                        _Context.Entry(terceiros).Property(x => x.DataCadastro).IsModified = false;
                        _Context.SaveChanges();

                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        terceiros.DataCadastro = DateTime.Now;
                        _Context.Financeriros.Add(terceiros);
                        _Context.SaveChanges();

                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    AjusteContextoEditar();
                    return View(terceiros);
                }
               
            }
            catch (Exception ex)
            {
                AjusteContextoEditar();
                return View(terceiros);
            }
        }

      
        public ActionResult Delete(int id)
        {

            var persertir = _Context.Financeriros.Find(id);
            _Context.Financeriros.Remove(persertir);
            _Context.SaveChanges();

            return RedirectToAction(nameof(Index));
           
        }

        private void AjusteContextoEditar()
        {
            var terceiros = _Context.Terceiros.ToList();
            ViewBag.Terceiros = new SelectList(terceiros, "Id", "Nome");
        }
    }
}

SistemaFinanceiro/Controllers/TerceirosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SistemaFinanceiro.Models;

namespace SistemaFinanceiro.Controllers
{
    [Authorize]
    public class TerceirosController : Controller
    {
        private AppDbContext _Context;

        public TerceirosController(AppDbContext context)
        {
            _Context = context;
        }
        
        // GET: Terceiros
        public ActionResult Index()
        {
            return View(_Context.Terceiros.ToList());
        }


        // GET: Terceiros/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id > 0)
            {
                var terceiros = _Context.Terceiros.Include(c => c.ListaDeFinanceriros).FirstOrDefault(c => c.Id == id);
                return View(terceiros);
            }
            else
            {
                return View(new Terceiros());
            }
        }

        // POST: Terceiros/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Terceiros terceiros)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (terceiros.Id > 0)
                    {
                        _Context.Entry(terceiros).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                        _Context.Entry(terceiros).Property(x => x.DataCadastro).IsModified = false;
                        _Context.SaveChanges();

                        return RedirectToAction(nameof(Index));
                    }
                    else
                    {
                        terceiros.DataCadastro = DateTime.Now;
                        _Context.Terceiros.Add(terceiros);
                        _Context.SaveChanges();

                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    return View(terceiros);
                }
               
            }
            catch (Exception ex)
            {
                return View(terceiros);
            }
        }

      
        public ActionResult Delete(int id)
        {

            var persertir = _Context.Terceiros.Find(id);
            _Context.Terceiros.Remove(persertir);
            _Context.SaveChanges();

            return RedirectToAction(nameof(Index));
           
        }
    }
}

SistemaFinanceiro/Controllers/UsuarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SistemaFinanceiro.Models;

namespace SistemaFinanceiro.Controllers
{
    [Authorize]
    public class UsuarioController : Controller
    {
        private AppDbContext _Context;

        public UsuarioController(AppDbContext context)
        {
            _Context = context;
        }
        
        // GET: Usuario
        public ActionResult Index()
        {
            return View();
        }


        public IActionResult IndexGrid(string search)
        {

            return PartialView(string.IsNullOrWhiteSpace(search) ? _Context.Usuario.AsQueryable() : _Context.Usuario.Where(c =>
                c.Nome.Contains(search) ||
                c.Email.Contains(search)));
        }

        // GET: Usuario/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id > 0)
            {
                return View(_Context.Usuario.Find(id));
            }
            else
            {
                return View(new Usuario());
            }
        }

        // POST: Usuario/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Usuario usuario)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (usuario.Id > 0)
                    {
                        var persertir = _Context.Usuario.Find(usuario.Id);

                        persertir.Nome = usuario.Nome;
                        persertir.Email = usuario.Email;
                        persertir.Senha = usuario.Senha;


                        return RedirectToAction(nameof(Index));


                    }
                    else
                    {
                        
                        _Context.Usuario.Add(usuario);
                        _Context.SaveChanges();

                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    return View(usuario);
                }
               
            }
            catch
            {
                return View(usuario);
            }
        }


      
        public ActionResult Delete(int id)
        {

            var persertir = _Context.Usuario.Find(id);
            _Context.Usuario.Remove(persertir);
            _Context.SaveChanges();

            return RedirectToAction(nameof(Index));
           
        }
    }
}

SistemaFinanceiro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Financeiro | Construtora </title>

    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="font-awesome/css/font-awesome.css" rel="stylesheet">

    <link href="css/animate.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">

</head>

<body>

    <div id="wrapper">

        <nav class="navbar-default navbar-static-side" role="navigation">
            <div class="sidebar-collapse">
                <ul class="nav metismenu" id="side-menu">
                    <li class="nav-header">
                        <div class="dropdown profile-element">
                            <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                                <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">Financeiro</strong>
                    </li>
                   
                        <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                        <li><a asp-area="" asp-controller="Usuario" asp-action="Index">Usuarios</a></li>
                        <li><a asp-area="" asp-controller="Terceiros" asp-action="Index">Terceiros</a></li>
                        <li><a asp-area="" asp-controller="Financeiro" asp-action="Index">Financeiro</a></li>                 

            </div>

        </nav>       

        <div id="page-wrapper" class="gray-bg">
            <div class="row border-bottom">
                <nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
                    <div class="navbar-header">
                        <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
                        <form role="search" class="navbar-form-custom" method="post" action="#">
                            <div class="form-group">

                            </div>
                        </form>
                    </div>
                    <ul class="nav navbar-top-links navbar-right">
                        <li>
                            <a href="#">
                                <i class="fa fa-sign-out"></i> Acesso
                            </a>
                        </li>
                    </ul>

                </nav>
            </div>
            <div class="wrapper wrapper-content animated fadeInRight">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="text-center m-t-lg">

                            <small>
                            </small>
                        </div>
                    </div>
                </div>
                <div class="container body-content">
                    @RenderBody()
                    <hr />
                    <footer>
                       @*<p>&copy; 2019 - SistemaFinanceiro</p>*@
                    </footer>
                </div>
            </div>
            <div class="footer">
                <div class="pull-right">

                </div>
                <div>
                    <strong>Empresa</strong>Company &copy; 2019-2019
                </div>
            </div>

        </div>

    </div>
  

    <!-- Mainly scripts -->
    <script src="js/jquery-3.1.1.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/plugins/metisMenu/jquery.metisMenu.js"></script>
    <script src="js/plugins/slimscroll/jquery.slimscroll.min.js"></script>

    <!-- Custom and plugin javascript -->
    <script src="js/inspinia.js"></script>
    <script src="js/plugins/pace/pace.min.js"></script>
    @RenderSection("Scripts", required: false)

</body>

</html>